[package]
name = "numtest"
version = "0.7.0"
authors = ["Tamas Kis"]
edition = "2024"
description = "Unit testing for numerical methods."
keywords = ["testing", "numerical", "mathematics", "assertions"]
categories = ["development-tools::testing", "science", "mathematics"]
documentation = "https://docs.rs/numtest"
repository = "https://github.com/tamaskis/numtest"
license = "MIT OR Apache-2.0"

exclude = [".github/", ".vscode/", "book/", ".gitignore", "Cargo.lock"]

[package.metadata.docs.rs]
rustdoc-args = [ "--html-in-header", "src/docs-header.html" ]

[dev-dependencies]
nalgebra = "0.35.0"
ndarray = "0.17.2"